# Generated by Django 4.2 on 2024-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='position_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='position_y',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
