# Generated by Django 4.2 on 2024-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0002_memo_position_x_memo_position_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='text',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
