# Generated by Django 4.2 on 2024-05-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0004_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
