# Generated by Django 4.2 on 2024-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservkdata',
            name='access_token',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
