# Generated by Django 4.2 on 2024-05-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_auth', '0002_uservkdata_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservkdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='uservkdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='uservkdata',
            name='photo_50',
        ),
    ]
