name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
      - name: Lint with ruff
        run: |
         ruff check
      - name: coverage report
        run: |
          coverage run manage.py test
          coverage report
      - name: Django tests
        run: |
          python manage.py test memorizer.tests