name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgre5eeeee3xf
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt
          TESTING_PROCEDURE="TRUE"
          echo "GIT_ACTIONS_TESTING_PROCEDURE=$TESTING_PROCEDURE" >> $GITHUB_ENV
          export GIT_ACTIONS_TESTING_PROCEDURE="TRUE"
          echo $GIT_ACTIONS_TESTING_PROCEDURE
      - name: Lint with ruff
        run: |
         ruff check
      - name: Django tests
        run: |
          python main/manage.py test memorizer.tests
      - name: coverage report
        run: |
          coverage run main/manage.py test
          coverage report