name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r main/requirements.txt
          TESTING_PROCEDURE="TRUE"
          echo "GIT_ACTIONS_TESTING_PROCEDURE=$TESTING_PROCEDURE" >> $GITHUB_ENV
          export GIT_ACTIONS_TESTING_PROCEDURE="TRUE"
          echo $GIT_ACTIONS_TESTING_PROCEDURE
      - name: Lint with ruff
        run: |
         ruff check
      - name: Django tests
        run: |
          python main/manage.py test memorizer.tests
      - name: coverage report
        run: |
          coverage run main/manage.py test
          coverage report